// ─── RANKS ────────────────────────────────────────────────────────────────────
export const RANKS = [
  { name: 'Bronze',          min: 0,     max: 1000,  icon: '🥉', color: '#CD7F32' },
  { name: 'Silver',          min: 1000,  max: 3000,  icon: '🥈', color: '#A0A0A0' },
  { name: 'Gold',            min: 3000,  max: 7000,  icon: '🥇', color: '#FFD700' },
  { name: 'Platinum',        min: 7000,  max: 15000, icon: '💎', color: '#9B7FEA' },
  { name: 'Master Animator', min: 15000, max: 999999,icon: '🏆', color: '#FFB347' },
];

// ─── LEADERBOARD ──────────────────────────────────────────────────────────────
export const LEADERBOARD = [
  { rank:1, name:'AnimaKing',   xp:12400, level:37, badge:'Platinum', avatar:'AK', color:'#FFB347' },
  { rank:2, name:'PixelDancer', xp:11200, level:35, badge:'Platinum', avatar:'PD', color:'#9B7FEA' },
  { rank:3, name:'FrameForge',  xp:9800,  level:33, badge:'Gold',     avatar:'FF', color:'#5B9CF6' },
  { rank:4, name:'TweenQueen',  xp:8700,  level:31, badge:'Gold',     avatar:'TQ', color:'#52C97C' },
  { rank:5, name:'BoneBreaker', xp:7500,  level:28, badge:'Gold',     avatar:'BB', color:'#FF8FAB' },
  { rank:6, name:'LoopMaster',  xp:6200,  level:26, badge:'Gold',     avatar:'LM', color:'#4ECDC4' },
  { rank:7, name:'KeyKid',      xp:4100,  level:21, badge:'Silver',   avatar:'KK', color:'#9B7FEA' },
];

// ─── DAILY QUESTS ─────────────────────────────────────────────────────────────
export const QUESTS = [
  { id:1, title:'Complete a lesson',       xp:30, icon:'📚', max:1  },
  { id:2, title:'Open the editor',         xp:20, icon:'✏️',  max:1  },
  { id:3, title:'Ask Ani a question',      xp:40, icon:'🤖', max:1  },
  { id:4, title:'Earn 100 XP today',       xp:50, icon:'⭐', max:100},
  { id:5, title:'Watch a tutorial video',  xp:20, icon:'🎥', max:1  },
  { id:6, title:'Pass a quiz correctly',   xp:35, icon:'🧠', max:1  },
  { id:7, title:'Visit your profile',      xp:15, icon:'👤', max:1  },
];

// ─── WORLDS & LESSONS ─────────────────────────────────────────────────────────
export const WORLDS = [
  {
    id:'foundations', title:'Animation Foundations',
    color:'#5B9CF6', icon:'🎬', unlockedByDefault:true,
    desc:'Master the building blocks every animator needs',
    lessons:[
      { id:'f1', title:'Welcome to Animation',   xp:30,  time:'3 min', diff:'Beginner',
        icon:'👋', desc:'Discover what animation is and why these principles exist.',
        content:`Animation is the art of creating the illusion of movement. Before digital tools existed, Disney animators Frank Thomas and Ollie Johnston studied real life — how things move, feel weight, and express emotion.\n\nThey distilled their discoveries into 12 core principles. These aren't rules to restrict you — they're tools to make your work feel alive. Every great animator from the Disney golden age to modern Pixar uses these principles as their foundation.\n\nYour journey starts here.`,
        quiz:{ q:'Who codified the 12 Principles of Animation?', opts:['Pixar','Disney animators','DreamWorks','Warner Bros'], correct:1 },
        task:'Write down one animated movie you love. What makes the characters feel real to you?',
        videoId:null },
      { id:'f2', title:'Timing — The Heartbeat', xp:45,  time:'5 min', diff:'Beginner',
        icon:'⏱️', desc:'Timing controls how fast or slow actions occur and communicates weight.',
        content:`Timing is how many frames an action takes. More frames = slower, heavier action. Fewer frames = faster action.\n\nTiming communicates WEIGHT. A heavy boulder takes many frames to stop. A ping-pong ball stops almost instantly. This is why timing is called "the heartbeat of animation."\n\nA character reaching for a coffee cup takes different timing than reaching for a grenade. The SAME action, with different timing, tells a completely different story about who this character is and what's at stake.`,
        quiz:{ q:'MORE frames in an action creates:', opts:['Faster motion','Heavier, slower motion','Sharper edges','No change'], correct:1 },
        task:'Imagine a ball dropped. How many frames for a heavy bowling ball vs a lightweight foam ball? Write your estimates.',
        videoId:'YOHp9Dj4jMs' },
      { id:'f3', title:'Spacing — The Soul',     xp:45,  time:'5 min', diff:'Beginner',
        icon:'📏', desc:'Spacing is where you place drawings between keyframes.',
        content:`Spacing refers to the distribution of drawings between keyframes. Even spacing = mechanical, robotic motion. Uneven spacing = organic, living motion.\n\nThe closer drawings are together, the slower the movement reads. The further apart, the faster. Most natural motion has "ease in" (starts slow) and "ease out" (ends slow) with a burst of speed in the middle.\n\nImagine a pendulum: it slows at the top, speeds through the bottom, slows again at the other top. Spacing and timing work together — you cannot understand one without the other.`,
        quiz:{ q:'Even spacing between frames creates:', opts:['Natural motion','Organic feel','Mechanical/robotic motion','Heavy motion'], correct:2 },
        task:'Describe 5 positions of a ball rolling to a stop. Where are the drawings clustered?',
        videoId:null },
      { id:'f4', title:'Squash & Stretch',       xp:50,  time:'6 min', diff:'Beginner',
        icon:'🫧', desc:'The most fundamental principle of life in animation.',
        content:`Squash and stretch is the illusion of flexibility and mass. When a rubber ball hits the ground, it SQUASHES (flattens). As it bounces up, it STRETCHES (elongates in the direction of motion).\n\nThe critical rule: VOLUME must stay consistent. If you squash something wide, it cannot also get taller. Think of it like clay — you can reshape it, but the amount never changes.\n\nThis applies to everything — even rigid objects have subtle squash/stretch that implies weight.`,
        quiz:{ q:'What MUST stay consistent during squash and stretch?', opts:['The shape','The speed','The volume/mass','The color'], correct:2 },
        task:'Describe a ball at 3 stages: normal sphere, squashed on impact, stretched going up.',
        videoId:null },
      { id:'f5', title:'Anticipation',            xp:55,  time:'6 min', diff:'Beginner',
        icon:'⚡', desc:'Prepare the viewer before the main action for maximum impact.',
        content:`Anticipation is the preparation before a main action. Before a character JUMPS, they crouch down. Before a punch is thrown, the arm pulls back.\n\nAnticipation does two things:\n1) It signals to the viewer WHAT is about to happen\n2) It makes the main action feel MORE powerful by contrast\n\nWithout anticipation, actions feel sudden and unnatural. The SIZE of the anticipation should match the SIZE of the action. A small step needs a small anticipation. A superhero leap needs an enormous, dramatic anticipation.`,
        quiz:{ q:'The SIZE of anticipation should match the:', opts:['Number of frames','Size of the main action','Character height','Background complexity'], correct:1 },
        task:'Describe the anticipation pose for: a cat pouncing on a toy mouse.',
        videoId:null },
      { id:'f6', title:'The 12 Principles',       xp:65,  time:'8 min', diff:'Beginner',
        icon:'📋', desc:'A complete tour of all 12 Disney animation principles.',
        content:`The 12 Principles of Animation:\n\n1. Squash & Stretch\n2. Anticipation\n3. Staging\n4. Straight Ahead & Pose-to-Pose\n5. Follow Through & Overlapping Action\n6. Slow In & Slow Out\n7. Arcs\n8. Secondary Action\n9. Timing\n10. Exaggeration\n11. Solid Drawing\n12. Appeal\n\nEach principle works in harmony with the others. A great animation layers all 12 simultaneously. Your journey in Animotion will teach you to use each one fluently.`,
        quiz:{ q:'How many Disney Animation Principles are there?', opts:['8','10','12','14'], correct:2 },
        task:'Pick your two favourite principles. Explain why they excite you most as an animator.',
        videoId:'haa7n3UGyDc' },
    ],
  },
  {
    id:'motion', title:'Motion & Physics',
    color:'#9B7FEA', icon:'🌀', unlockedByDefault:false,
    desc:'Understand how objects move through the physical world',
    lessons:[
      { id:'m1', title:'Arcs of Motion',           xp:65,  time:'7 min', diff:'Intermediate',
        icon:'🌀', desc:'Natural motion follows curved paths, not straight lines.',
        content:`Almost nothing in nature moves in a straight line. Arms swing in arcs. Heads rotate in arcs. Even a thrown ball follows a parabolic arc.\n\nWhen objects move in straight lines in animation, they look mechanical and wrong. The key is to plan the PATH OF ACTION — the invisible line an object traces through space — before you animate it.\n\nDraw it out first, then guide your drawings along that curve. Straight-line exceptions exist for robots or supernatural motion, but those are deliberate choices, not accidents.`,
        quiz:{ q:'Why do animators use arcs instead of straight lines?', opts:["It's easier","Natural motion follows curved paths","It looks modern","Straight lines are faster"], correct:1 },
        task:'Trace the arc path for a full arm wave — down at the side, up overhead, back down.',
        videoId:null },
      { id:'m2', title:'Slow In & Slow Out',        xp:65,  time:'7 min', diff:'Intermediate',
        icon:'📈', desc:'Ease in and ease out create organic, natural motion.',
        content:`Slow In (Ease In): more drawings cluster at the END of a movement — the object decelerates into its final position.\n\nSlow Out (Ease Out): more drawings cluster at the START — the object accelerates from rest.\n\nMost natural movements use BOTH. A pendulum: starts slow (Slow Out from rest), speeds up through the bottom, slows at the top (Slow In to a stop).\n\nIn software this is called "easing." The default linear interpolation makes everything feel robotic. Adding easing is often the fastest way to make animation feel natural.`,
        quiz:{ q:'"Ease Out" means the object:', opts:['Slows at the end','Accelerates from rest','Stays at constant speed','Reverses direction'], correct:1 },
        task:'Plot 9 frames of a bouncing ball. Cluster positions near the top, spread them apart at the bottom.',
        videoId:null },
      { id:'m3', title:'Follow Through & Overlap',  xp:70,  time:'8 min', diff:'Intermediate',
        icon:'🌊', desc:'Secondary parts lag behind and continue after the main action.',
        content:`Follow Through: after the main body stops, appendages continue to move before settling. If a character stops running suddenly, their hair and clothing continue forward momentarily.\n\nOverlapping Action: different parts of the body move at different times and rates. A character's arm doesn't start moving at the exact same frame as their legs. Things overlap.\n\nThese two principles working together are what make characters feel like they have real physical mass.`,
        quiz:{ q:'Overlapping action means:', opts:['Everything moves at once','Different body parts move at different times','The background moves','Colors change'], correct:1 },
        task:"Describe what happens to a horse's tail and mane when the horse suddenly stops galloping.",
        videoId:null },
      { id:'m4', title:'Straight Ahead vs Pose-to-Pose', xp:70, time:'8 min', diff:'Intermediate',
        icon:'🔀', desc:'Two fundamental methods for creating animation.',
        content:`STRAIGHT AHEAD: animate from the first drawing to the last in sequence. Produces spontaneous, fluid results. Great for fire, water, organic chaos.\n\nPOSE-TO-POSE: define your key poses first (start, middle, end), then fill in between. Gives control over timing, composition, and story beats. Best for character performance and dramatic scenes.\n\nMost professionals use BOTH — Pose-to-Pose for structure, Straight Ahead for secondary elements. For beginners, start with Pose-to-Pose.`,
        quiz:{ q:'Pose-to-pose animation is best for:', opts:['Fire and water','Character performance and drama','Quick exploratory sketches','Texture work'], correct:1 },
        task:'Name 2 scenarios where you would use Straight Ahead, and 2 where you would use Pose-to-Pose.',
        videoId:null },
      { id:'m5', title:'Secondary Action',          xp:75,  time:'8 min', diff:'Intermediate',
        icon:'🎭', desc:'Supporting actions that reinforce and enrich the main action.',
        content:`Secondary action supports and enhances the main action without stealing focus from it.\n\nIf a character is walking (main action), their arms swinging is secondary. If a character is crying (main action), wringing their hands is secondary.\n\nThe critical rule: secondary action must NOT compete with the main action. It must be subtle enough to enrich, but never so prominent that the viewer's eye is pulled away from what matters.`,
        quiz:{ q:'A secondary action should:', opts:['Compete for attention','Distract the viewer','Support and enrich the main action','Always be bigger'], correct:2 },
        task:"List 3 good secondary actions for a character who is trying to pretend they're not nervous.",
        videoId:null },
    ],
  },
  {
    id:'character', title:'Character & Acting',
    color:'#FF8FAB', icon:'🎭', unlockedByDefault:false,
    desc:'Bring personality and emotion into every frame',
    lessons:[
      { id:'c1', title:'Weight & Mass',   xp:80, time:'9 min', diff:'Advanced',
        icon:'⚖️', desc:'Making objects and characters feel like they have real physical weight.',
        content:`Weight is the single most important quality separating beginner animation from professional work.\n\nTo convey weight:\n1) Timing — heavy things accelerate slowly and take time to stop\n2) Squash — heavy things deform more on impact\n3) Anticipation — picking up a heavy object requires more preparation\n4) Reaction — when a heavy object lands, surfaces react\n5) Breathing — heavy characters show more effort in their chest\n\nThink about how your entire body engages differently picking up a 1kg box versus a 30kg box. ALL of that is animation data.`,
        quiz:{ q:'Which is the most important factor in conveying weight?', opts:['Character size','Timing','Shape design','Color palette'], correct:1 },
        task:"Describe frame-by-frame what happens when a character picks up a box that's far heavier than expected.",
        videoId:null },
      { id:'c2', title:'Exaggeration',    xp:80, time:'9 min', diff:'Advanced',
        icon:'💥', desc:'Push your animation beyond realistic limits for maximum impact.',
        content:`Exaggeration doesn't mean making things unrealistic — it means making them MORE true to what they are. Amplify the essence.\n\nIf a character is happy, don't just make them smile — make them glow, bounce on their toes, eyes wide with pure delight.\n\nChuck Jones said: "Animation is not the art of drawings that move but the art of movements that are drawn."\n\nExaggerate in the DIRECTION of truth, not away from it. Take what's real and amplify so it reads clearly on screen.`,
        quiz:{ q:'Exaggeration in animation is about:', opts:['Making things completely unrealistic','Amplifying the truth of what something is','Adding more frames','Changing colors'], correct:1 },
        task:'Take "person stepping on a Lego" and describe 3 exaggerated versions: subtle, medium, full cartoon.',
        videoId:null },
      { id:'c3', title:'Staging',         xp:75, time:'8 min', diff:'Advanced',
        icon:'🎥', desc:'Present your ideas so they are unmistakably clear.',
        content:`Staging is the presentation of an idea so it is completely and unmistakably clear. Every action, expression, and mood must be silhouette-readable.\n\nTest: make your character a solid black shape. You should still understand exactly what they are doing and feeling. If you can't tell, the staging is weak.\n\nRules: one clear centre of attention at a time. Don't have two important things happening simultaneously. Use the entire frame. The background should support, not compete.`,
        quiz:{ q:'A well-staged animation should be readable as a:', opts:['Detailed colour painting','Silhouette','3D wireframe','Pencil sketch'], correct:1 },
        task:"Describe how you'd stage a scene: a tiny mouse challenges a huge cat.",
        videoId:null },
      { id:'c4', title:'Appeal',          xp:85, time:'9 min', diff:'Advanced',
        icon:'✨', desc:'The quality that makes viewers want to look at your characters.',
        content:`Appeal doesn't mean cute — it means COMPELLING. A villain can have appeal through menace. A monster can have appeal through grotesque fascination.\n\nDesign rules for appeal:\n- Avoid perfect symmetry (slightly asymmetric is more interesting)\n- Use clear, readable shapes\n- Avoid tangents (accidental line alignments)\n- Give every character a unique silhouette\n- Round shapes = friendly; angular = sharp/dangerous\n\nAppeal is the difference between a technically correct drawing and one that feels ALIVE.`,
        quiz:{ q:'Appeal in animation means the character is:', opts:['Always cute','Always happy','Compelling and worth watching','Perfectly symmetrical'], correct:2 },
        task:'Design a character using only 3 shapes (circle, square, triangle). What personality do they have?',
        videoId:null },
      { id:'c5', title:'Solid Drawing',   xp:90, time:'10 min', diff:'Advanced',
        icon:'🏗️', desc:'Characters must feel like they exist in three-dimensional space.',
        content:`Solid drawing means your characters feel like they have volume, weight, and exist in 3D space — even in 2D animation.\n\nKey rules:\n- AVOID TWINS: when both sides of the body do the same thing, it looks flat. Always create asymmetry.\n- Use PERSPECTIVE: body parts closer to viewer appear larger\n- Maintain CONSISTENT VOLUME across frames\n- Think in 3D FORMS: cylinders for arms, spheres for heads, boxes for torsos\n- FORESHORTENING: a limb pointing at the camera appears shorter\n\nWhen you draw, feel like you're sculpting, not drawing.`,
        quiz:{ q:'"Avoiding twins" in animation means:', opts:['Never draw two characters','Avoid both sides doing the same thing','Keep the same pose','Avoid background symmetry'], correct:1 },
        task:"Draw or describe the difference between a 'twin pose' (boring) and an asymmetric, dynamic version.",
        videoId:null },
    ],
  },
  {
    id:'advanced', title:'Advanced Techniques',
    color:'#FFB347', icon:'🔥', unlockedByDefault:false,
    desc:'Polish your animations to a professional standard',
    lessons:[
      { id:'a1', title:'Walk Cycles',       xp:100, time:'12 min', diff:'Advanced',
        icon:'🚶', desc:'The foundational looping animation every animator must master.',
        content:`A standard walk cycle is 8 drawings (at 24fps, two steps).\n\nKey positions:\n1. CONTACT — heel of front foot touches ground\n2. DOWN — body at lowest point, absorbing impact\n3. PASSING — weight leg is vertical, free leg passes under\n4. UP — body at highest point, front leg about to swing\n\nThe walk cycle reveals CHARACTER:\n- Bouncy = happy/energetic\n- Slouched = tired/defeated\n- Long strides = confident\n- Short steps = nervous/uncertain\n- Stiff = angry/tense\n\nArms swing opposite to legs. Head bobs counter to hip movement.`,
        quiz:{ q:'A standard walk cycle has how many key drawings?', opts:['4','6','8','12'], correct:2 },
        task:'Slowly walk across a room and identify each key position: Contact, Down, Passing, Up.',
        videoId:'mHEPGwQbZy4' },
      { id:'a2', title:'Lip Sync Basics',   xp:90,  time:'10 min', diff:'Advanced',
        icon:'💬', desc:'Synchronize mouth shapes to dialogue for believable speech.',
        content:`Lip sync is syncing mouth shapes to the phonemes (sounds) of dialogue. You don't animate every sound — pick the ACCENTED sounds.\n\nKey mouth shapes:\n- A/I: mouth wide open\n- E: stretched wide, almost closed\n- O/U: round opening\n- F/V: bottom lip under upper teeth\n- M/B/P: lips pressed completely together\n- REST: natural, slightly open position\n\nProcess: listen to dialogue. Write out phoneme sequence. Mark accented sounds. Animate mouth on accented sounds only.\n\nCritical: the EYES and brows carry the emotional story more than the mouth.`,
        quiz:{ q:'When animating lip sync, focus on:', opts:['Every single phoneme','Only vowels','The accented/stressed sounds','Only consonants'], correct:2 },
        task:"Write the phoneme sequence for: 'Hello! How are you today?' Mark the stressed sounds.",
        videoId:null },
      { id:'a3', title:'Camera & Angles',   xp:85,  time:'9 min', diff:'Advanced',
        icon:'📹', desc:'Use camera angles purposefully to tell your story.',
        content:`Camera angles carry meaning:\n\n- LOW ANGLE (looks up): Subject appears powerful, threatening, heroic\n- HIGH ANGLE (looks down): Subject appears small, vulnerable\n- EYE LEVEL: Neutral, observational\n- DUTCH ANGLE (tilted): Unease, tension, something is wrong\n- WIDE SHOT: Establishes environment, shows scale\n- CLOSE-UP: Intimacy, emotion, important detail\n\nA moving camera should always have a REASON — it reveals information or creates emotion. A camera that moves without purpose is just noise.`,
        quiz:{ q:'A low angle camera makes the subject appear:', opts:['Small and vulnerable','Powerful and imposing','Neutral','Comedic'], correct:1 },
        task:"Choose 3 different camera angles for this scene: 'A child finds a mysterious locked door in their house.'",
        videoId:null },
      { id:'a4', title:'Polish & Final Pass',xp:100, time:'12 min', diff:'Advanced',
        icon:'💎', desc:'The professional secrets to taking animation from good to great.',
        content:`The final polish pass is where good animation becomes great. Professionals spend up to 50% of total time here.\n\nPolish checklist:\n✓ Smooth out hitches or stutters in motion\n✓ Add subtle secondary actions (blinks, breathing, weight shifts)\n✓ Check ALL arcs are clean\n✓ Ensure timing feels considered at EVERY frame\n✓ Add texture — not every action needs the same timing rhythm\n✓ Check silhouette at each key pose\n✓ Add moments of stillness — held poses communicate as much as movement\n✓ Have someone unfamiliar with the scene watch it cold\n\nThe difference between polished and unpolished is felt in RHYTHM.`,
        quiz:{ q:'How much time do professionals often spend polishing?', opts:['About 5%','About 15%','Up to 50%','Only a few minutes'], correct:2 },
        task:'Watch any 30-second animated clip. Write down 5 subtle polish details you notice.',
        videoId:null },
    ],
  },
];

export const ALL_LESSONS = WORLDS.flatMap((w) =>
  w.lessons.map((l) => ({
    ...l,
    worldId:    w.id,
    worldTitle: w.title,
    worldColor: w.color,
    worldIcon:  w.icon,
  }))
);
